version: "{build}"

environment:
  nodejs_version: "10"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run compile
  - npm run all-tests
  - npm run analyze-coverage && npm run codecov

build: off
